id: wordpress-accessible-wpconfig

info:
  name: WordPress wp-config Detection
  author: 0xpugazh
  severity: medium
  description: WordPress `wp-config` was discovered. This file is remotely accessible and its content available for reading.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 30
  tags: wordpress,backup

http:
  - method: GET
    path:
      - '{{BaseURL}}/config.php.zip'
      - '{{BaseURL}}/config.php.tar.gz'
      - '{{BaseURL}}/config.php.new'
      - '{{BaseURL}}/common/config.php.new'
      - '{{BaseURL}}/wp-config.php.bk'

    stop-at-first-match: true

    matchers-condition: or
    matchers:
      - type: word
        words:
          - "DB_NAME"
          - "DB_PASSWORD"
          - "DBNAME"
        part: body
        condition: and

      - type: word
        part: body
        words:
          - "DBNAME"
          - "PASSWORD"
        condition: and
